
services:

  nest-blog-api_postgres:
    container_name: nest-blog-api_postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile   
    environment:      
      POSTGRES_DB: nest-blog     
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: postgres
    ports:
      - "${NEST_BLOG_API_POSTGRES_PORT}:${NEST_BLOG_API_POSTGRES_PORT}"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nest-blog-api_pgweb: 
    container_name: nest-blog-api_pgweb
    image: sosedoff/pgweb
    ports:
      - "${NEST_BLOG_API_PG_WEB_PORT}:8081"
    environment: 
      PGWEB_DATABASE_URL: "postgres://postgres:postgres@nest-blog-api_postgres:${NEST_BLOG_API_POSTGRES_PORT}/nest-blog?sslmode=disable"
    restart: unless-stopped   

  nest-blog-api_server:
    container_name: nest-blog-api_server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    environment:
      NEST_BLOG_API_TYPEORM_HOST: $NEST_BLOG_API_TYPEORM_HOST
      NEST_BLOG_API_POSTGRES_PORT: $NEST_BLOG_API_POSTGRES_PORT
    ports:
      - "${NEST_BLOG_API_SERVER_PORT}:3001"
    restart: unless-stopped