
services:
  blog-db_test-int:
    image: postgres
    container_name: blog-db_test-int
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_DATABASE}
      
  pgadpgadmin_test-int:
    image: dpage/pgadmin4
    container_name: pgadmin_test-int
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 

  redis-db_test-int:
    container_name: redis-db_test-int
    image: redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"

  redis-commander_test-int:
    container_name: redis-commander_test-int
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      REDIS_HOSTS: "local:${REDIS_COMMANDER_HOST}:${REDIS_PORT}"
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"