query {
  getBlogPost(id: "XXX"){
    	id
      title
      body
      author {
        id
        name
      }  
    	comments {
            id
            body
            author {
                id
                name
            }
      }
  }
}